# Generated by Django 5.0.3 on 2024-03-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
